version: '1.0'
services:
  propiedades:
    image: dannyhs/nurairbnb:lastest
    ports:
      - 8085:8080
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 45
  comentarios:
    image: cristhian1995/diplomado-containers:latest
    ports:
      - 8081:8083
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 45
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 45
  
networks:
  default:
     driver: bridge
