version: '1.0'
services:
  propiedades:
    image: nahomy/propiedades:tag
    ports:
      - 8085:8080
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 45
    environment:
      - DATA_BASE_URL=jdbc:postgresql://postgres:5433/nurairbnbc
      - DATA_BASE_USERNAME=postgres
      - DATA_BASE_PASSWORD=postgres
      - PORT=8085
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nurairbnbc
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 45
  
networks:
  default:
     driver: bridge