server:
  port: ${PORT:8082}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nurairbnb
    username: postgres
    password: danny

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /
