name: Staging to digitalocean

on:
  push:
    tags:
      - stage-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/setup-java@v3
      - name: Copy Docker file
        run: cp ${{ github.workspace }}/docker-deploy/Dockerfile ${{ github.workspace }}/Dockerfile
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: WebDanny/nurairbnb
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses:  actions/setup-java@v3

      - name: Get tag name
        uses: nahomy/get-tag@v2.1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait


