name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
            Host staging
              HostName 165.232.137.243
              User root
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END


      - name: Stop the server
        run: ssh staging 'cd /home/nurairbnb && sh deploy.sh && docker-compose up -d'
